Sample PHP Project
guibranco/BancosBrasileiros pull request #237
Opened 2023-06-26 20:51 UTC by AmolKumarGupta

I also created a readme for project

2023-06-26 20:56 UTC, AmolKumarGupta commented
### An Example 

![image](https://github.com/guibranco/BancosBrasileiros/assets/88397611/0001ad2f-caf1-45c5-80e6-cab6107010b9)

2023-06-26 21:54 UTC, guibranco requested changes

2023-06-26 21:54 UTC, guibranco commented on schemas/Bank.php
The file in the schema folder should not be changed.
They should be a DTO only. Not a real implementation.

We can duplicate it and add the behavior of Bank.php to a folder called Src for example, and also make it available to the Packagist/Composer folder. 

Let me know if you are ok with that, otherwise I will do the changes when I have a chance.

2023-06-27 14:27 UTC, AmolKumarGupta commented on schemas/Bank.php
Great. I will do it asap

2023-06-27 14:40 UTC, guibranco commented on schemas/Bank.php
Thanks!

2023-06-29 21:08 UTC, guibranco approved these changes

2023-06-29 21:09 UTC, guibranco approved these changes

2023-06-29 21:16 UTC, merged

2023-06-29 21:17 UTC, guibranco commented
Done! Thanks @AmolKumarGupta